[package]
name = "ff_power_ranking_generator"
version = "0.1.0"
authors = ["Joe Kari <kari7003@gmail.com>"]

[dependencies]
requests = "0.0.30"
serde = "1.0.79"
serde_derive = "1.0.79"
serde_json = "1.0.31"
